/**
 * Orchestrator Workspace v5.0 — Agent Provenance Badge
 *
 * Renders a 3px glowing neon top-border on the parent card +
 * a small badge (bottom-left) showing model icon + label.
 *
 * Design: Subtle neon core & badges — not full surface tinting.
 * Uses the parallel agent color palette (separate from engine colors).
 */

import { motion } from 'framer-motion'
import { cn } from '@/lib/utils'
import { getAgentColor } from '@/lib/orchestrator/workspace/v5/agent-registry'
import type { AgentColorConfig } from '@/lib/orchestrator/workspace/v5/v5-types'

interface AgentProvenanceBadgeProps {
  modelId: string
  /** If true, renders only the badge without the top-border glow */
  badgeOnly?: boolean
  className?: string
}

export function AgentProvenanceBadge({
  modelId,
  badgeOnly = false,
  className,
}: AgentProvenanceBadgeProps) {
  const agent = getAgentColor(modelId)

  return (
    <>
      {/* Neon top-border (3px glow) — rendered as absolute overlay on parent */}
      {!badgeOnly && <NeonTopBorder agent={agent} />}

      {/* Badge (bottom-left) */}
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.2, duration: 0.2 }}
        className={cn(
          'inline-flex items-center gap-1 px-1.5 py-0.5 rounded',
          'text-[9px] font-mono font-medium tracking-wide',
          'border backdrop-blur-sm',
          className,
        )}
        style={{
          color: agent.neonColor,
          borderColor: `${agent.neonColor}30`,
          backgroundColor: `${agent.neonColor}08`,
        }}
        title={`Generated by ${agent.displayName}`}
      >
        <AgentIcon color={agent.neonColor} />
        <span>{agent.displayName}</span>
      </motion.div>
    </>
  )
}

// ─── Neon Top Border ─────────────────────────────────────────────────────────

function NeonTopBorder({ agent }: { agent: AgentColorConfig }) {
  return (
    <motion.div
      initial={{ scaleX: 0 }}
      animate={{ scaleX: 1 }}
      transition={{ duration: 0.4, ease: 'easeOut' }}
      className="absolute top-0 left-0 right-0 h-[3px] origin-left"
      style={{
        background: `linear-gradient(90deg, ${agent.neonColor}00, ${agent.neonColor}, ${agent.neonColor}00)`,
        boxShadow: `0 0 8px ${agent.neonColor}60, 0 0 16px ${agent.neonColor}20`,
      }}
    />
  )
}

// ─── Agent Icon ──────────────────────────────────────────────────────────────

function AgentIcon({ color }: { color: string }) {
  return (
    <svg
      width="8"
      height="8"
      viewBox="0 0 8 8"
      fill="none"
      className="flex-shrink-0"
    >
      <circle
        cx="4"
        cy="4"
        r="3"
        stroke={color}
        strokeWidth="1"
        opacity="0.8"
      />
      <circle
        cx="4"
        cy="4"
        r="1.2"
        fill={color}
        opacity="0.9"
      />
    </svg>
  )
}

// ─── Utility: Wrapper for cards ──────────────────────────────────────────────

/**
 * Wraps a BentoCard in a relative container with agent provenance.
 * Use this in StreamingBentoGrid to wrap card content.
 */
export function AgentProvenanceWrapper({
  modelId,
  children,
}: {
  modelId: string | null
  children: React.ReactNode
}) {
  if (!modelId) return <>{children}</>

  return (
    <div className="relative">
      <AgentProvenanceBadge modelId={modelId} />
      {children}
      {/* Badge positioned at bottom-left of parent */}
      <div className="absolute bottom-2 left-2 z-10">
        <AgentProvenanceBadge modelId={modelId} badgeOnly />
      </div>
    </div>
  )
}
