import { DEMO_THREAD } from '@/lib/demo-thread'
import { PROJECTED_3Y_ADVANTAGE } from '@/lib/grow-simulation-data'
import { recommendationDetails } from '@/pages/grow/recommendation-detail-data'
import type {
  CanonicalUniverseV1,
  DashboardActivityEntity,
  ExecuteActionEntity,
  GovernAuditEntryEntity,
  ProtectThreatEntity,
  RecommendationEntity,
} from './types'

const VERIFIED_DECISIONS = 10191
const PENDING_REVIEW_DECISIONS = 55
const FLAGGED_DECISIONS = 3

const DASHBOARD_ACTIVITIES: DashboardActivityEntity[] = [
  {
    id: 'ACT-001',
    kind: 'protect',
    label: `Flagged suspicious transfer to ${DEMO_THREAD.criticalAlert.merchant}`,
    relativeTime: '2m ago',
  },
  {
    id: 'ACT-002',
    kind: 'grow',
    label: 'Savings goal projection updated',
    relativeTime: '15m ago',
  },
  {
    id: 'ACT-003',
    kind: 'execute',
    label: 'Auto-paid electricity bill',
    relativeTime: '1h ago',
  },
  {
    id: 'ACT-004',
    kind: 'govern',
    label: `Compliance check passed (${DEMO_THREAD.complianceScore}/100)`,
    relativeTime: '2h ago',
  },
  {
    id: 'ACT-005',
    kind: 'system',
    label: `Monthly savings baseline ${formatUsd(DEMO_THREAD.monthlySavings)} confirmed`,
    relativeTime: '3h ago',
  },
]

const PROTECT_THREATS: ProtectThreatEntity[] = [
  {
    id: DEMO_THREAD.criticalAlert.id,
    merchant: DEMO_THREAD.criticalAlert.merchant,
    amountUsd: DEMO_THREAD.criticalAlert.amount,
    confidence: DEMO_THREAD.criticalAlert.confidence,
    severity: 'Critical',
    description: 'Unusual transaction pattern',
    relativeTime: '4h ago',
    sortOrder: 8,
  },
  {
    id: 'THR-002',
    merchant: 'Unknown Vendor',
    amountUsd: 1200,
    confidence: 0.87,
    severity: 'High',
    description: 'Unrecognized merchant',
    relativeTime: '1d ago',
    sortOrder: 7,
  },
  {
    id: 'THR-003',
    merchant: 'Travel Agency XYZ',
    amountUsd: 3400,
    confidence: 0.72,
    severity: 'Medium',
    description: 'International wire transfer',
    relativeTime: '3d ago',
    sortOrder: 6,
  },
  {
    id: 'THR-004',
    merchant: 'Gas Station ATM',
    amountUsd: 800,
    confidence: 0.65,
    severity: 'Low',
    description: 'Unusual ATM withdrawal',
    relativeTime: '1w ago',
    sortOrder: 4,
  },
  {
    id: 'THR-005',
    merchant: 'Crypto Exchange',
    amountUsd: 5000,
    confidence: 0.91,
    severity: 'Medium',
    description: 'High-risk category transfer',
    relativeTime: '5d ago',
    sortOrder: 5,
  },
]

/** Derived from recommendation-detail-data.ts (single source of truth for Grow). */
const RECOMMENDATIONS: RecommendationEntity[] = recommendationDetails.map(r => ({
  id: `REC-${String(r.id).padStart(3, '0')}`,
  title: r.title,
  monthlySavingsUsd: r.monthlySavings,
  annualSavingsUsd: r.annualSavings,
  confidence: r.confidence,
}))

const EXECUTE_ACTIONS: ExecuteActionEntity[] = [
  {
    id: 'EXE-001',
    title: 'Portfolio rebalance',
    engine: 'Execute',
    amountLabel: '$12,400',
    confidence: 0.97,
    timestampLabel: '14:28',
    description: '$12,400 transfer from Cash Reserve to Growth Equity Index',
    urgency: 'high',
    impact: {
      approved: 'Allocation adjusted and tracked in the govern audit trace.',
      deferred: 'Portfolio keeps current drift and review is deferred to next cycle.',
    },
    reversible: true,
    expiresIn: '14h',
    factors: [
      { label: 'Concentration risk', value: 0.91 },
      { label: 'Cash allocation', value: 0.87 },
      { label: 'Volatility outlook', value: 0.78 },
    ],
    executionType: 'hybrid',
    category: 'investment',
    sourceEngine: 'Execute',
    rollbackWindowHours: 24,
    steps: [
      { id: 'EXE-001-S1', label: 'Analyze current allocation', description: 'AI scans portfolio drift against target allocation model', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-001-S2', label: 'Calculate optimal rebalance', description: 'Determine minimum-trade path to restore target weights', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '3s' },
      { id: 'EXE-001-S3', label: 'Review transfer plan', description: 'You review the $12,400 transfer details and tax impact', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~2 min' },
      { id: 'EXE-001-S4', label: 'Queue transfers for approval', description: 'Transfer orders queued for your brokerage confirmation', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '5s' },
      { id: 'EXE-001-S5', label: 'Confirm and log', description: 'Transaction receipts are logged to the immutable audit ledger', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '1s' },
    ],
  },
  {
    id: 'EXE-002',
    title: 'Flag suspicious merchant charge',
    engine: 'Protect',
    amountLabel: formatUsd(DEMO_THREAD.criticalAlert.amount),
    confidence: DEMO_THREAD.criticalAlert.confidence,
    timestampLabel: '14:15',
    description: `Suspicious ${formatUsd(DEMO_THREAD.criticalAlert.amount)} charge at ${DEMO_THREAD.criticalAlert.merchant} flagged for dispute`,
    urgency: 'high',
    impact: {
      approved: 'Charge flagged and dispute workflow queued for your review.',
      deferred: 'Transaction remains active and fraud exposure window extends.',
    },
    reversible: true,
    expiresIn: '6h',
    factors: [
      { label: 'Merchant risk', value: 0.87 },
      { label: 'Amount anomaly', value: 0.71 },
      { label: 'Geo mismatch', value: 0.65 },
    ],
    executionType: 'semi-auto',
    category: 'protection',
    sourceEngine: 'Protect',
    sourceEntityId: DEMO_THREAD.criticalAlert.id,
    rollbackWindowHours: 48,
    steps: [
      { id: 'EXE-002-S1', label: 'Detect anomaly', description: 'AI flagged suspicious pattern matching known fraud vectors', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '1s' },
      { id: 'EXE-002-S2', label: 'Flag transaction', description: 'Transaction flagged for your review with supporting evidence', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-002-S3', label: 'Approve fraud flag & dispute', description: 'You confirm the flag and initiate dispute workflow', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~1 min' },
      { id: 'EXE-002-S4', label: 'File dispute', description: 'Agent auto-files dispute with card issuer and logs evidence', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '8s' },
    ],
  },
  {
    id: 'EXE-003',
    title: 'Subscription consolidation',
    engine: 'Grow',
    amountLabel: 'Save $140/mo',
    confidence: 0.89,
    timestampLabel: '13:52',
    description: '3 overlapping media subscriptions detected — consolidation saves $140/mo',
    urgency: 'medium',
    impact: {
      approved: 'Estimated savings of $140/mo are queued for execution.',
      deferred: 'Current subscription stack remains unchanged.',
    },
    reversible: true,
    expiresIn: null,
    factors: [
      { label: 'Cost reduction', value: 0.92 },
      { label: 'Overlap confidence', value: 0.88 },
      { label: 'Billing category match', value: 0.82 },
    ],
    executionType: 'hybrid',
    category: 'savings',
    sourceEngine: 'Grow',
    sourceEntityId: 'REC-002',
    rollbackWindowHours: 72,
    steps: [
      { id: 'EXE-003-S1', label: 'Identify overlaps', description: 'AI analyzed billing categories and merchant codes across 12 active subscriptions', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '4s' },
      { id: 'EXE-003-S2', label: 'Propose cancellations', description: '3 subscriptions identified with 88% content overlap', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '2s' },
      { id: 'EXE-003-S3', label: 'Review cancellation list', description: 'You confirm which subscriptions to cancel', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~3 min' },
      { id: 'EXE-003-S4', label: 'Queue cancellation requests', description: 'Cancellation requests queued for your confirmation', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '15s' },
      { id: 'EXE-003-S5', label: 'Verify and log savings', description: 'Log confirmed cancellations and project $140/mo savings to ledger', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '3s' },
    ],
  },
  {
    id: 'EXE-004',
    title: 'Recommend invoice archive',
    engine: 'Execute',
    amountLabel: '-',
    confidence: 0.78,
    timestampLabel: '11:20',
    description: '47 paid Q3 invoices identified for compliance cold-storage archive',
    urgency: 'medium',
    impact: {
      approved: 'Invoice archive queued for your confirmation and governance logging.',
      deferred: 'Invoice archive remains unchanged and queue re-checks in 24h.',
    },
    reversible: false,
    expiresIn: '3d',
    factors: [
      { label: 'Document age', value: 0.84 },
      { label: 'Archive confidence', value: 0.77 },
      { label: 'Policy fit', value: 0.73 },
    ],
    executionType: 'auto',
    category: 'compliance',
    sourceEngine: 'Execute',
    steps: [
      { id: 'EXE-004-S1', label: 'Scan invoice queue', description: 'AI identified 47 fully paid invoices older than 90 days', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '6s' },
      { id: 'EXE-004-S2', label: 'Approve archive batch', description: 'You confirm the batch archive is acceptable', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~1 min' },
      { id: 'EXE-004-S3', label: 'Queue archive and index', description: 'Archive batch queued for your confirmation and metadata indexing', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '30s' },
    ],
  },
  {
    id: 'EXE-005',
    title: 'Pay electricity bill',
    engine: 'Execute',
    amountLabel: '$187',
    confidence: 0.99,
    timestampLabel: '10:30',
    description: '$187 scheduled auto-payment from Checking to ConEdison',
    urgency: 'low',
    impact: {
      approved: 'Payment executes and receipt is logged in the audit ledger.',
      deferred: 'Payment is deferred and reminder is raised to the queue.',
    },
    reversible: true,
    expiresIn: '18h',
    factors: [
      { label: 'Payment confidence', value: 0.99 },
      { label: 'Schedule consistency', value: 0.93 },
      { label: 'Balance sufficiency', value: 0.95 },
    ],
    executionType: 'auto',
    category: 'savings',
    sourceEngine: 'Execute',
    rollbackWindowHours: 24,
    steps: [
      { id: 'EXE-005-S1', label: 'Verify payment schedule', description: 'AI confirmed recurring payment matches billing cycle', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '1s' },
      { id: 'EXE-005-S2', label: 'Check balance', description: 'Sufficient funds verified in Checking account', actor: 'agent', status: 'completed', requiresConsent: false, estimatedDuration: '1s' },
      { id: 'EXE-005-S3', label: 'Approve payment', description: 'You confirm the $187 auto-payment', actor: 'user', status: 'current', requiresConsent: true, estimatedDuration: '~30s' },
      { id: 'EXE-005-S4', label: 'Process payment', description: 'Agent submits payment and logs receipt to audit ledger', actor: 'agent', status: 'waiting', requiresConsent: false, estimatedDuration: '3s' },
    ],
  },
]

const GOVERN_AUDIT_ENTRIES: GovernAuditEntryEntity[] = [
  {
    id: 'GV-2026-0319-847',
    timestampIso: '2026-03-19T14:28:00-04:00',
    type: 'Execute',
    action: 'Portfolio rebalance',
    confidence: 0.97,
    evidence: 12,
    status: 'Verified',
  },
  {
    id: 'GV-2026-0319-846',
    timestampIso: '2026-03-19T14:15:00-04:00',
    type: 'Protect',
    action: `Flag suspicious merchant charge (${formatUsd(DEMO_THREAD.criticalAlert.amount)})`,
    confidence: DEMO_THREAD.criticalAlert.confidence,
    evidence: 9,
    status: 'Verified',
  },
  {
    id: 'GV-2026-0319-845',
    timestampIso: '2026-03-19T13:52:00-04:00',
    type: 'Grow',
    action: 'Subscription consolidation',
    confidence: 0.89,
    evidence: 7,
    status: 'Verified',
  },
  {
    id: 'GV-2026-0319-844',
    timestampIso: '2026-03-19T11:20:00-04:00',
    type: 'Execute',
    action: 'Invoice archive recommended',
    confidence: 0.78,
    evidence: 5,
    status: 'Pending review',
  },
  {
    id: 'GV-2026-0318-843',
    timestampIso: '2026-03-18T16:42:00-04:00',
    type: 'Protect',
    action: 'Unusual transaction',
    confidence: 0.92,
    evidence: 10,
    status: 'Verified',
  },
  {
    id: 'GV-2026-0318-842',
    timestampIso: '2026-03-18T10:18:00-04:00',
    type: 'Grow',
    action: 'Goal update',
    confidence: 0.86,
    evidence: 6,
    status: 'Verified',
  },
  {
    id: 'GV-2026-0317-841',
    timestampIso: '2026-03-17T14:12:00-04:00',
    type: 'Execute',
    action: 'Scheduled payment verified',
    confidence: 0.91,
    evidence: 8,
    status: 'Verified',
  },
  {
    id: 'GV-2026-0317-840',
    timestampIso: '2026-03-17T09:40:00-04:00',
    type: 'Govern',
    action: 'Policy update',
    confidence: 0.97,
    evidence: 15,
    status: 'Verified',
  },
]

export const CANONICAL_UNIVERSE: CanonicalUniverseV1 = {
  schemaVersion: '1.1.0',
  generatedAt: '2026-03-19T14:30:00-04:00',
  metrics: {
    systemConfidence: DEMO_THREAD.systemConfidence,
    complianceScore: DEMO_THREAD.complianceScore,
    pendingActions: DEMO_THREAD.pendingActions,
    monthlySavingsCurrentUsd: DEMO_THREAD.monthlySavings,
    monthlySavingsPotentialUsd: RECOMMENDATIONS.reduce((s, r) => s + r.monthlySavingsUsd, 0),
    decisionsAuditedTotal: DEMO_THREAD.decisionsAudited,
    verifiedDecisions: VERIFIED_DECISIONS,
    pendingReviewDecisions: PENDING_REVIEW_DECISIONS,
    flaggedDecisions: FLAGGED_DECISIONS,
    emergencyFund: {
      percent: DEMO_THREAD.emergencyFund.percent,
      currentUsd: DEMO_THREAD.emergencyFund.current,
      targetUsd: DEMO_THREAD.emergencyFund.target,
    },
    engineBreakdown: { Protect: 4102, Grow: 3287, Execute: 1850, Govern: 1010 },
    platformProfileCount: 184_290,
    architecturalTrust: {
      autoExecutionsWithoutConsent: 0,
      auditCoveragePercent: 100,
      falsePositiveRate: 0.001,
      llmRetentionDays: 0,
      llmTrainingOptOut: true,
    },
    cohort: {
      recommendationAcceptanceRate: 0.89,
      avgMonthlySavingsUsd: 583,
      fraudTrend: {
        label: 'Card-not-present fraud up 23% this quarter',
        changePercent: 23,
        period: 'Q1 2026',
        factors: [
          { label: 'Online merchant category risk', value: 0.82 },
          { label: 'Cross-border transaction velocity', value: 0.74 },
          { label: 'New device fingerprint frequency', value: 0.68 },
        ],
      },
      cohortSize: 12847,
      projected3yAdvantageUsd: PROJECTED_3Y_ADVANTAGE,
      protectPerformance: {
        riskIncidentsFlagged: 24,
        avgMonthlyExposureUsd: 280,
      },
    },
  },
  entities: {
    criticalAlert: {
      id: DEMO_THREAD.criticalAlert.id,
      amountUsd: DEMO_THREAD.criticalAlert.amount,
      merchant: DEMO_THREAD.criticalAlert.merchant,
      confidence: DEMO_THREAD.criticalAlert.confidence,
      cardLast4: DEMO_THREAD.criticalAlert.cardLast4 ?? '4821',
      signalId: DEMO_THREAD.criticalAlert.signalId ?? 'PRT-2026-0216-003',
    },
    protectThreats: PROTECT_THREATS,
    recommendations: RECOMMENDATIONS,
    executeActions: EXECUTE_ACTIONS,
    governAuditEntries: GOVERN_AUDIT_ENTRIES,
    dashboardActivities: DASHBOARD_ACTIVITIES,
  },
  /** @future — Cross-engine causal links for audit trail features. Not yet consumed by UI. */
  relations: {
    alertToAction: {
      [DEMO_THREAD.criticalAlert.id]: ['EXE-002'],
    },
    recommendationToAction: {
      'REC-002': ['EXE-003'],
    },
    actionToDecision: {
      'EXE-001': ['GV-2026-0319-847'],
      'EXE-002': ['GV-2026-0319-846'],
      'EXE-003': ['GV-2026-0319-845'],
      'EXE-004': ['GV-2026-0319-844'],
    },
  },
}

function formatUsd(value: number): string {
  return `$${value.toLocaleString()}`
}
