/**
 * Orchestrator Workspace v4.0 — Dynamic Suggestion Bar
 *
 * Horizontal scrollable strip of proactive DynamicSuggestionCards.
 * Cards are generated by suggestion-engine based on UserContext.
 * Clicking a card triggers the workspace-flow-engine pipeline.
 */

import { useCallback, useRef, useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { cn } from '@/lib/utils'
import { useWorkbenchContext } from '@/contexts/WorkbenchContext'
import { SuggestionCard } from './SuggestionCard'
import { executeSuggestionFlow } from '@/lib/orchestrator/workspace/workspace-flow-engine'
import { staggerContainer, fadeUp } from '@/lib/motion-presets'
import type { DynamicSuggestionCard } from '@/lib/orchestrator/workspace/workspace-types'

export function DynamicSuggestionBar() {
  const { state, dispatch } = useWorkbenchContext()
  const suggestions = state.workspace.activeSuggestions
  const userContext = state.workspace.userContext
  const scrollRef = useRef<HTMLDivElement>(null)
  const [canScrollLeft, setCanScrollLeft] = useState(false)
  const [canScrollRight, setCanScrollRight] = useState(false)

  // Check scroll state
  const updateScrollState = useCallback(() => {
    const el = scrollRef.current
    if (!el) return
    setCanScrollLeft(el.scrollLeft > 0)
    setCanScrollRight(el.scrollLeft + el.clientWidth < el.scrollWidth - 1)
  }, [])

  useEffect(() => {
    updateScrollState()
    const el = scrollRef.current
    if (!el) return
    el.addEventListener('scroll', updateScrollState, { passive: true })
    return () => el.removeEventListener('scroll', updateScrollState)
  }, [updateScrollState, suggestions])

  const scroll = useCallback((direction: 'left' | 'right') => {
    const el = scrollRef.current
    if (!el) return
    const amount = direction === 'left' ? -240 : 240
    el.scrollBy({ left: amount, behavior: 'smooth' })
  }, [])

  const handleSuggestionSelect = useCallback(
    async (suggestion: DynamicSuggestionCard) => {
      if (!userContext) return
      try {
        await executeSuggestionFlow(suggestion, userContext, dispatch)
      } catch (err) {
        console.error('[DynamicSuggestionBar] Flow execution failed:', err)
        // Auto-open chat drawer for fallback conversational disambiguation
        if (!state.workspace.chatDrawerOpen) {
          dispatch({ type: 'TOGGLE_CHAT_DRAWER' })
        }
      }
    },
    [userContext, dispatch, state.workspace.chatDrawerOpen],
  )

  if (suggestions.length === 0) return null

  return (
    <div className="relative">
      {/* Scroll fade edges */}
      {canScrollLeft && (
        <div className="absolute left-0 top-0 bottom-0 w-8 bg-gradient-to-r from-black/80 to-transparent z-10 pointer-events-none" />
      )}
      {canScrollRight && (
        <div className="absolute right-0 top-0 bottom-0 w-8 bg-gradient-to-l from-black/80 to-transparent z-10 pointer-events-none" />
      )}

      {/* Scroll buttons (desktop only) */}
      {canScrollLeft && (
        <button
          onClick={() => scroll('left')}
          className="absolute left-1 top-1/2 -translate-y-1/2 z-20 hidden md:flex items-center justify-center w-7 h-7 rounded-full bg-white/[0.08] hover:bg-white/[0.15] text-white/50 hover:text-white/80 transition-colors"
        >
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
            <path d="M7.5 2.5L4 6L7.5 9.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
          </svg>
        </button>
      )}
      {canScrollRight && (
        <button
          onClick={() => scroll('right')}
          className="absolute right-1 top-1/2 -translate-y-1/2 z-20 hidden md:flex items-center justify-center w-7 h-7 rounded-full bg-white/[0.08] hover:bg-white/[0.15] text-white/50 hover:text-white/80 transition-colors"
        >
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
            <path d="M4.5 2.5L8 6L4.5 9.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
          </svg>
        </button>
      )}

      {/* Scrollable card strip */}
      <motion.div
        ref={scrollRef}
        variants={staggerContainer}
        initial="hidden"
        animate="visible"
        className="flex gap-3 overflow-x-auto px-4 py-3 scrollbar-none"
        style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}
      >
        {suggestions.map((suggestion) => (
          <motion.div key={suggestion.id} variants={fadeUp}>
            <SuggestionCard
              suggestion={suggestion}
              onSelect={handleSuggestionSelect}
            />
          </motion.div>
        ))}
      </motion.div>
    </div>
  )
}
